### ISSUE TITLE
Support for Full Page Component?

### ISSUE THREAD

**Issue by davidreyg** [joserick/laravel-livewire-discover#2]
I'm using [https://github.com/apiato/apiato](url) framework and i can't make it work.

`<?php

return [

    /*
    |---------------------------------------------------------------------------
    | Class Namespaces
    |---------------------------------------------------------------------------
    |
    | This values sets the class namespace for Livewire component classes in
    | your application. This is used to discover the Livewire components.
    |
    */

    'class_namespaces' => [
        // 'prefix' => '//namespace//',
        'root' => 'App\\Containers\\AppSection\\Authentication\\UI\\WEB\\Components',
    ],
];`

I have my component here 
`<?php

namespace App\Containers\AppSection\Authentication\UI\WEB\Components;

use Livewire\Component;

class Counter extends Component
{
    public $count = 1;

    public function increment()
    {
        $this->count++;
    }

    public function decrement()
    {
        $this->count--;
    }

    public function render()
    {
        return view('appSection@authentication::counter');
    }
}`

and the app.layout, I just ran the command in livewire docs so its in /resources/views/components/views/layouts/app.blade.php
So, The component is rendering when i call the route

![image](https://github.com/joserick/laravel-livewire-discover/assets/19297294/a2042b35-87ba-434d-b632-796bb03110df)

but when i hit buttons, display the image above.

any help?

**Comment by joserick** [comment]
Hi,

Can you give me an example of how you are calling the component? since it should be `<livewire:root-counter />` and apparently it is trying to search for the component with everything and namespace.

In any case, I will try to download Apiato and try it, maybe it will be some clash between parcel companies.

**Comment by davidreyg** [comment]
Hi. thx for your reply. 
From the official documentation.
https://livewire.laravel.com/docs/quickstart
I'm trying to display a full component layout 

```Register a route for the component
Open the routes/web.php file in your Laravel application and add the following code:

use App\Livewire\Counter;
 
Route::get('/counter', Counter::class);```

BTW, when using tthe way you say: `<livewire:root-counter />` works!

**Comment by joserick** [comment]
Ah! I already understood, you are loading the component directly from the "Route::get" class, the problem is that "Livewire-Discover" using this form does not know the prefix so it uses the entire path, so you have to define the prefix and the name directly in the component:

```php
class Counter extends Component
{
    public $count = 1;

    function getName()
    {
        return 'root-counter'; // <-- <livewire:root-counter /> Defining the prefix with the name name
    }
```

I will try to have this done automatically, otherwise I will add it to the documentation for these cases.

Thanks for reporting the problem.

**Comment by davidreyg** [comment]
Wow! @joserick thanks man. It's working now! :)
