### ISSUE TITLE
Publish not working

### ISSUE THREAD

**Issue by rajeev-k-tomy** [joserick/laravel-livewire-discover#5]
When I try this command:

```
php artisan vendor:publish --tag livewire-discover-config
```

I get the output:

 > INFO  No publishable resources for tag [livewire-discover-config].

**Comment by joserick** [comment]
Hi @rajeev-k-tomy 

Sorry for the delay, I was traveling.

I have done a fresh install from zero of "Laravel" more "Laravel Livewire Discover" without any problems; I can see that this error only appears when the installation is not done using composer "composer require joserick/laravel-livewire-discover"

![Captura desde 2024-09-12 19-46-38](https://github.com/user-attachments/assets/9fb4fd73-f0db-40ba-b80d-0fbe4475a62b)

I don't know if there is some error at the time of installation that is not allowing it to finish and because of this the command "php artisan vendor:publish --tag livewire-discover-config" cannot be executed.
